bitbake.conf: globally define KERNEL_PACKAGE_NAME
A number of recipes rely on hard coded
kernel prefix set by KERNEL_PACKAGE_NAME
when including modules. This leads to build
time failures such as.

ERROR: Nothing RPROVIDES 'kernel-module-*'

Commit globally defines variable so that
recipes aren't reliant on hardcoded 'kernel'
prefix.

Commit also updates variables

STAGING_KERNEL_DIR
STAGING_KERNEL_BUILDDIR

STAGING_KERNEL_DIR and STAGING_KERNEL_BUILDDIR get
changed from default defined in bitbake.conf in
the kernel.bbclass. The reason was to set these
variables to directories under WORKDIR in alternate
kernel recipes (I.e. where KERNEL_PACKAGE_NAME != kernel)
so that they may build in parallel with the default
kernel without clobbering. The issue is that the variables
only get changed in kernel recipes. So, other recipes
such as perf and make-mod-scripts don't know the
location of virtual/kernel WORKDIR.

Solution is to include KERNEL_PACKAGE_NAME in
STAGING_KERNEL_DIR and STAGING_KERNEL_BUILDDIR
so recipes like perf and make-mod-scripts can
find virtual/kernel source and solve the
clobbering of build artifacts issue.

Signed-off-by: Vincent Davis Jr <vince@underview.tech>